name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: zygisk-il2cppdumper
        path: out/magisk_module_release/
